name: Build with MPLAB X and an XC compiler
description: This action builds a MPLAB X project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.00"
  compiler_name:
    description: The name of the XC Complier to use
    required: true
    default: "xc8"
  compiler_version:
    description: Version of the compiler to use
    required: true
    default: "1.34"
  additional_packages:
    description: Any additional packages needed to build the project
    required: false
  install_ipe:
    description: Set to 1 if they IPE should be installed in the image
    required:  false
    default: "0"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
    - ${{ inputs.mplabx_version }}
    - ${{ inputs.compiler_name }}
    - ${{ inputs.compiler_version }}
    - ${{ inputs.additional_packages }}
    - ${{ inputs.install_ipe }}
