name: Build with MPLAB X and an XC compiler
description: This action builds a MPLAB X project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
  mplabx_version:
    description: Version of MPLAB X to use
    required: true
    default: "6.00"
  compiler_name:
    description: The name of the XC Complier to use
    required: true
    default: "xc8"
  complier_version:
    description: Version of the compiler to use
    required: true
    default: "1.34"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mplabx_version }}
    - ${{ inputs.complier_name }}
    - ${{ inputs.complier_version }}
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
